# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_awdb_wrappers", use_symbols = TRUE, package_name = "awdb")

#' @usage NULL
#' @useDynLib awdb, .registration = TRUE
NULL

parse_station_dataset_json <- function(x) .Call(wrap__parse_station_dataset_json, x)

parse_station_forecast_set_json <- function(x) .Call(wrap__parse_station_forecast_set_json, x)

parse_station_reference_json <- function(x, reference_type) .Call(wrap__parse_station_reference_json, x, reference_type)

parse_station_metadataset_json <- function(x) .Call(wrap__parse_station_metadataset_json, x)


# nolint end
